name: Main pipeline

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v2
      - name: Run ShellCheck
        run: |
          shellcheck scripts/*.sh

      - name: Run gofmt
        run: |
          ./scripts/checks.sh
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go get gotest.tools/gotestsum

      - name: modVerify
        run: go mod verify

      - name: modTidy
        run: go mod tidy

      - name: vet
        run: go vet ./...

      - name: ensure compilation
        env:
          GOOS: linux
        run: go build

      - name: gotestsum
        # only run tests on linux, there are a number of things that won't allow the tests to run on anything else
        # many (maybe, all?) images used can only be build on Linux, they don't have Windows in their manifest, and
        # we can't put Windows Server in "Linux Mode" in Github actions
        # another, host mode is only available on Linux, and we have tests around that, do we skip them?
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: gotestsum --format short-verbose ./...
